name: Push to Another Repository

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      #      - name: run NodeJs
      #        run: |
      #          npm install
      #          npm run start
      - name: to target repo
        uses: s0/git-publish-subdir-action@develop
        env:
          # 换成自己的目标仓库
          REPO: https://github.com/wushuo894/BgmCache.git
          # 目标分支
          BRANCH: cache
          # 要推送的目录
          FOLDER: bgm
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
