name: Push to Another Repository

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run NodeJs
        run: |
          npm install
          npm run start
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: master
          FOLDER: bgm
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_DIR: bgm
